//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Headache.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public int Id { get; set; }
        public string VisaNum1 { get; set; }
        public string VisaNum2 { get; set; }
        public string VisaNum3 { get; set; }
        public string VisaNum4 { get; set; }
        public string Name { get; set; }
        public int Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int Nationality { get; set; }
    }
}
